#!/usr/bin/env php
<?php

namespace Clever;

define('CLEVER_ROOT_DIR', __DIR__."/..");

if ( ! file_exists(__DIR__.'/../vendor/autoload.php'))
    throw new \Exception("Autoload file not found.");

require __DIR__.'/../vendor/autoload.php';

(new CleverApplication())
    ->bootstrap()
    ->run();
